trigger:
- Azure

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m venv .venv
    source .venv/bin/activate
    pip install -r requirements.txt
  displayName: 'Set up Python environment'

- script: |
    source .venv/bin/activate
    python generate_data.py
  displayName: 'Run data generation script'